[package]
name = "w-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
darling = "0.21.0"
quote = "1.0.40"
syn = "2.0.104"
w-ddd = { version = "0.1.0", path = "../w-ddd" }
